import 'package:flutter_test/flutter_test.dart';
import 'package:furn_app/features/catalog/data/ikea_catalog_ingest.dart';
import 'package:furn_app/shared/models/models.dart';

/// The catalogue is scraped from a live IKEA storefront, so ingestion treats it
/// as untrusted: it validates, drops the unusable, counts the drops, and maps
/// what survives into the one model the engine speaks — CatalogProduct.
///
/// The record fixtures follow the generator's guaranteed schema exactly (all
/// numerics as floats, the four aesthetic keys always present), and the bad
/// ones are the real records the prompt names.
void main() {
  const ingest = IkeaCatalogIngest();

  Map<String, dynamic> record({
    String id = 's1',
    String name = 'KIVIK 3-seat sofa',
    String category = 'sofa',
    double? price = 2495.0,
    double width = 228.0,
    double length = 95.0,
    double height = 83.0,
    String link = 'https://www.ikea.com/sa/en/p/kivik-s1/',
    String image = 'https://www.ikea.com/sa/en/images/products/kivik.jpg',
    String model = 'https://api.furn-app.com/assets/models/kivik_s1.usdz',
    List<String> colors = const ['Dark Grey'],
    String material = 'Polyester fabric, solid pine',
    String style = 'Contemporary Dark',
    String vibe = 'Grounded, masculine, cosy',
  }) =>
      {
        'id': id,
        'product_name': name,
        'store': 'IKEA KSA',
        'category': category,
        'price_sar': price,
        'urls': {
          'product_link': link,
          'image_url': image,
          '3d_model_url': model,
        },
        'spatial_attributes': {
          'width_cm': width,
          'length_cm': length,
          'height_cm': height,
        },
        'aesthetic_features': {
          'primary_colors': colors,
          'material': material,
          'style': style,
          'vibe': vibe,
        },
      };

  CatalogProduct only(List<dynamic> records) => ingest.run(records).products.single;

  group('the axis mapping — the part that breaks silently', () {
    test('IKEA length_cm (Depth) becomes depthCm, width_cm becomes widthCm', () {
      // The footprint the solver builds is widthCm x depthCm. Swap these and
      // every item rotates 90 degrees through the walls while the app looks OK.
      final p = only([record(width: 228, length: 95, height: 83)]);
      expect(p.widthCm, 228); // side-to-side
      expect(p.depthCm, 95); //  front-to-back = IKEA "length"
      expect(p.heightCm, 83);
    });

    test('an int survives if the file is ever regenerated by an older gen', () {
      // The model uses (num).toDouble(), not `as double`.
      final r = record()
        ..['spatial_attributes'] = {
          'width_cm': 228, // int, not 228.0
          'length_cm': 95,
          'height_cm': 83,
        };
      final p = only([r]);
      expect(p.widthCm, 228.0);
      expect(p.depthCm, 95.0);
    });
  });

  group('validation drops the unusable and counts it', () {
    test('the NEIDEN bed (height 8 cm — a floor clearance, not a bed) is dropped',
        () {
      final res = ingest.run([
        record(id: 'neiden', category: 'bed', width: 90, length: 200, height: 8),
      ]);
      expect(res.keptCount, 0);
      expect(res.dropped['neiden'], DropReason.belowCategoryFloor);
    });

    test('the HÄGERNÄS table (1.2 x 40 x 4 cm) is dropped', () {
      final res = ingest.run([
        record(
            id: 'hag', category: 'dining_table', width: 1.2, length: 40, height: 4),
      ]);
      expect(res.dropped['hag'], DropReason.belowCategoryFloor);
    });

    test('an axis over 400 cm is rejected', () {
      final res = ingest.run([record(id: 'huge', width: 450)]);
      expect(res.dropped['huge'], DropReason.badAxis);
    });

    test('a zero or missing axis is rejected', () {
      final res = ingest.run([
        record(id: 'zero', width: 0),
        {
          ...record(id: 'missing'),
          'spatial_attributes': {'width_cm': 100.0, 'height_cm': 80.0},
        },
      ]);
      expect(res.dropped['zero'], DropReason.badAxis);
      expect(res.dropped['missing'], DropReason.badAxis);
    });

    test('a product link off the /sa/en/ storefront is rejected', () {
      final res = ingest.run([
        record(id: 'wrong', link: 'https://www.ikea.com/us/en/p/kivik/'),
        record(id: 'phish', link: 'https://ikea.evil.com/sa/en/p/x/'),
      ]);
      expect(res.dropped['wrong'], DropReason.badProductLink);
      expect(res.dropped['phish'], DropReason.badProductLink);
    });

    test('an empty id is rejected', () {
      final res = ingest.run([record(id: '')]);
      expect(res.dropHistogram[DropReason.emptyId], 1);
    });

    test('a non-object record is dropped, not thrown on', () {
      final res = ingest.run(['not a record', 42, record(id: 'ok')]);
      expect(res.keptCount, 1);
      expect(res.dropHistogram[DropReason.notObject], 2);
    });

    test('a duplicate id keeps the first and drops the rest', () {
      // The source scrapes a live site and can repeat a record ("×2");
      // duplicate productIds would collapse in the engine's byId map.
      final res = ingest.run([
        record(id: 'dup'),
        record(id: 'dup'),
        record(id: 'unique'),
      ]);
      expect(res.products.map((p) => p.productId), ['dup', 'unique']);
      expect(res.dropHistogram[DropReason.duplicateId], 1);
    });

    test('the histogram counts every drop reason', () {
      final res = ingest.run([
        record(id: 'a', price: null),
        record(id: 'b', width: 0),
        record(id: 'c'), // kept
      ]);
      expect(res.keptCount, 1);
      expect(res.dropCount, 2);
    });
  });

  group('price null means unknown, never free', () {
    test('a null price is dropped and counted, not coerced to zero', () {
      final res = ingest.run([record(id: 'noprice', price: null)]);
      expect(res.products, isEmpty);
      expect(res.dropped['noprice'], DropReason.unknownPrice);
    });

    test('a real price is carried through as SAR', () {
      final p = only([record(price: 1649.0)]);
      expect(p.price, 1649.0);
      expect(p.currency, 'SAR');
    });
  });

  group('the mapping into CatalogProduct', () {
    test('IKEA category folds into the engine seven, original kept as sub', () {
      expect(only([record(category: 'armchair')]).category,
          RecommendationCategory.sofa);
      expect(only([record(category: 'wardrobe', width: 100, length: 60,
              height: 200)]).category,
          RecommendationCategory.storage);
      expect(only([record(category: 'desk', width: 120, length: 60,
              height: 74)]).subcategory,
          'desk');
    });

    test('aesthetic fields land where scoring reads them', () {
      final p = only([record(
        colors: ['Dark Grey', 'Black'],
        material: 'Polyester fabric, solid pine',
        style: 'Contemporary Dark',
        vibe: 'Grounded, cosy',
      )]);
      expect(p.colorTags, ['Dark Grey', 'Black']);
      expect(p.materialTags, ['Polyester fabric', 'solid pine']);
      expect(p.styleTags, contains('Contemporary Dark'));
      expect(p.styleTags, contains('Grounded')); // vibe feeds aesthetic match
    });

    test('empty aesthetic values are tolerated, never null', () {
      final p = only([record(colors: const [], material: '', style: '', vibe: '')]);
      expect(p.colorTags, isEmpty);
      expect(p.materialTags, isEmpty);
      expect(p.styleTags, isEmpty);
    });

    test('brand and supplier are set; product/image urls carried', () {
      final p = only([record()]);
      expect(p.brand, 'IKEA');
      expect(p.supplier, 'IKEA KSA');
      expect(p.productUrl, startsWith('https://www.ikea.com/sa/en/'));
      expect(p.imageUrl, isNotEmpty);
    });

    test('AR stays off: usdz kept but no glb and arReady false', () {
      final p = only([record()]);
      expect(p.modelUsdzUrl, contains('.usdz'));
      expect(p.modelGlbUrl, isEmpty);
      expect(p.arReady, isFalse);
      expect(p.hasArModel, isFalse); // the "see it in your room" button stays hidden
    });
  });

  group('the name↔dimensions transpose warning (LACK, SANDSBERG)', () {
    test('a swapped width/depth vs the name is warned, not dropped', () {
      // Name says 55x110, record says width 110 / length(depth) 55 → swapped.
      final res = ingest.run([
        record(
            id: 'lack',
            name: 'LACK side table, 55x110 cm',
            category: 'coffee_table',
            width: 110,
            length: 55,
            height: 45),
      ]);
      expect(res.keptCount, 1); // kept
      expect(res.warnings.single, contains('lack'));
    });

    test('a name whose dimensions agree raises no warning', () {
      final res = ingest.run([
        record(
            id: 'agree',
            name: 'EKTORP sofa 218x88 cm',
            width: 218,
            length: 88,
            height: 88),
      ]);
      expect(res.warnings, isEmpty);
    });
  });

  test('ingestion is deterministic', () {
    final a = ingest.run([record(id: 'x'), record(id: 'y', price: null)]);
    final b = ingest.run([record(id: 'x'), record(id: 'y', price: null)]);
    expect(a.products.map((p) => p.productId),
        b.products.map((p) => p.productId));
    expect(a.dropped, b.dropped);
  });
}
