#!/usr/bin/env python3
"""
USDZ -> self-contained HTML preview (pure stdlib, no dependencies).

USDZ opens natively only on Apple platforms (Quick Look). This turns any
package generated by generate_3d_catalog.py / generate_catalog_fin_usdz.py
into a single .html file that renders the same geometry in any browser with
raw WebGL — no libraries, no network — so the models can be checked on
Windows, Android and Linux too.

The viewport draws a 10cm floor grid with 1m majors. That is the point of
the preview: these assets are authored at true real-world scale, and a grid
the model is measured against shows it at a glance.

Usage:  python3 tools/preview_usdz.py <file.usdz> [-o out.html]
                                      [--title "..."] [--meta key=value ...]
"""

import argparse
import json
import os
import re
import zipfile

VIEWER_TEMPLATE = r"""<title>__TITLE__</title>
<style>
  :root {
    color-scheme: light dark;
    --ground: #E9ECEF;
    --surface: #FFFFFF;
    --surface-2: #F3F5F7;
    --line: #D3D8DE;
    --ink: #171A1E;
    --muted: #5D666F;
    --accent: #0E6E62;
    --accent-soft: #D7E9E5;
    --stage-top: #DFE4E8;
    --stage-bottom: #C9D0D6;
    --grid-minor: rgba(23, 26, 30, 0.10);
    --grid-major: rgba(14, 110, 98, 0.45);
    --sans: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
    --mono: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;
  }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      --ground: #101315;
      --surface: #191D21;
      --surface-2: #1F2429;
      --line: #2C3238;
      --ink: #E7ECF0;
      --muted: #98A2AC;
      --accent: #55D6C2;
      --accent-soft: #163832;
      --stage-top: #22282D;
      --stage-bottom: #14181B;
      --grid-minor: rgba(231, 236, 240, 0.12);
      --grid-major: rgba(85, 214, 194, 0.50);
    }
  }
  :root[data-theme="dark"] {
    --ground: #101315;
    --surface: #191D21;
    --surface-2: #1F2429;
    --line: #2C3238;
    --ink: #E7ECF0;
    --muted: #98A2AC;
    --accent: #55D6C2;
    --accent-soft: #163832;
    --stage-top: #22282D;
    --stage-bottom: #14181B;
    --grid-minor: rgba(231, 236, 240, 0.12);
    --grid-major: rgba(85, 214, 194, 0.50);
  }

  * { box-sizing: border-box; }
  body {
    margin: 0;
    background: var(--ground);
    color: var(--ink);
    font-family: var(--sans);
    line-height: 1.5;
    -webkit-font-smoothing: antialiased;
  }
  .wrap {
    max-width: 1120px;
    margin: 0 auto;
    padding: clamp(20px, 4vw, 40px) clamp(16px, 4vw, 32px) 48px;
    display: flex;
    flex-direction: column;
    gap: 20px;
  }

  header { display: flex; flex-direction: column; gap: 8px; }
  .eyebrow {
    font-family: var(--mono);
    font-size: 12px;
    letter-spacing: 0.09em;
    text-transform: uppercase;
    color: var(--muted);
    display: flex;
    flex-wrap: wrap;
    gap: 6px 14px;
  }
  .eyebrow b { color: var(--accent); font-weight: 600; }
  h1 {
    margin: 0;
    font-size: clamp(21px, 3.1vw, 30px);
    font-weight: 620;
    letter-spacing: -0.021em;
    text-wrap: balance;
  }

  .stage {
    position: relative;
    border: 1px solid var(--line);
    border-radius: 10px;
    overflow: hidden;
    background: linear-gradient(to bottom, var(--stage-top), var(--stage-bottom));
    touch-action: none;
  }
  canvas { display: block; width: 100%; height: clamp(340px, 58vh, 560px); }
  .hint {
    position: absolute;
    left: 12px;
    bottom: 11px;
    font-family: var(--mono);
    font-size: 11.5px;
    color: var(--muted);
    background: color-mix(in srgb, var(--surface) 78%, transparent);
    border: 1px solid var(--line);
    border-radius: 6px;
    padding: 4px 9px;
  }
  .tools {
    position: absolute;
    right: 12px;
    top: 12px;
    display: flex;
    gap: 6px;
  }
  .tools button {
    font-family: var(--mono);
    font-size: 11.5px;
    letter-spacing: 0.04em;
    color: var(--ink);
    background: color-mix(in srgb, var(--surface) 88%, transparent);
    border: 1px solid var(--line);
    border-radius: 6px;
    padding: 5px 10px;
    cursor: pointer;
  }
  .tools button:hover { border-color: var(--accent); }
  .tools button[aria-pressed="true"] {
    background: var(--accent-soft);
    border-color: var(--accent);
    color: var(--accent);
  }
  .tools button:focus-visible,
  a:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }

  .specs {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(148px, 1fr));
    background: var(--surface);
    border: 1px solid var(--line);
    border-radius: 10px;
    overflow: hidden;
    margin: 0;
  }
  /* Rules on the cells, not gaps: a trailing empty grid track then reads as
     surface rather than a stray block of line colour. */
  .spec {
    padding: 13px 15px;
    border-right: 1px solid var(--line);
    border-bottom: 1px solid var(--line);
  }
  .spec dt {
    font-family: var(--mono);
    font-size: 10.5px;
    letter-spacing: 0.09em;
    text-transform: uppercase;
    color: var(--muted);
    margin: 0 0 4px;
  }
  .spec dd {
    margin: 0;
    font-family: var(--mono);
    font-size: 14px;
    font-variant-numeric: tabular-nums;
    overflow-wrap: anywhere;
  }
  .spec dd .u { color: var(--muted); font-size: 12px; }

  .note {
    background: var(--surface-2);
    border: 1px solid var(--line);
    border-left: 3px solid var(--accent);
    border-radius: 8px;
    padding: 14px 16px;
    font-size: 14.5px;
    color: var(--muted);
    max-width: 68ch;
  }
  .note strong { color: var(--ink); font-weight: 600; }
  .note code {
    font-family: var(--mono);
    font-size: 13px;
    background: var(--surface);
    border: 1px solid var(--line);
    border-radius: 4px;
    padding: 1px 5px;
    color: var(--ink);
  }
  .fallback { padding: 40px 24px; text-align: center; color: var(--muted); }
</style>

<div class="wrap">
  <header>
    <p class="eyebrow">__EYEBROW__</p>
    <h1>__HEADING__</h1>
  </header>

  <div class="stage">
    <canvas id="c">Your browser does not support WebGL.</canvas>
    <div class="tools">
      <button id="grid" aria-pressed="true">Grid</button>
      <button id="bbox" aria-pressed="false">Bounds</button>
      <button id="spin" aria-pressed="true">Spin</button>
    </div>
    <p class="hint">Drag to orbit &middot; scroll to zoom &middot; grid squares are 10&nbsp;cm</p>
  </div>

  <dl class="specs">__SPECS__</dl>

  <p class="note">__NOTE__</p>
</div>

<script>
const MODEL = __MODEL__;

const canvas = document.getElementById("c");
// Transparent so the stage's CSS gradient — which is theme-aware — shows
// through instead of a hardcoded clear colour.
const gl = canvas.getContext("webgl",
  { antialias: true, alpha: true, premultipliedAlpha: false });
if (!gl) {
  canvas.outerHTML = '<p class="fallback">This browser cannot render WebGL, ' +
    'so the 3D preview is unavailable.</p>';
} else {
  main();
}

function main() {
  const VS = `
    attribute vec3 aPos; attribute vec3 aNrm;
    uniform mat4 uProj, uView;
    varying vec3 vNrm, vPos;
    void main() {
      vNrm = aNrm; vPos = aPos;
      gl_Position = uProj * uView * vec4(aPos, 1.0);
    }`;
  const FS = `
    precision mediump float;
    uniform vec3 uColor; uniform float uAlpha;
    varying vec3 vNrm, vPos;
    void main() {
      vec3 n = normalize(vNrm);
      if (!gl_FrontFacing) n = -n;
      vec3 key = normalize(vec3(0.45, 0.85, 0.55));
      vec3 fill = normalize(vec3(-0.6, 0.35, -0.4));
      float l = 0.30 + 0.72 * max(dot(n, key), 0.0) + 0.20 * max(dot(n, fill), 0.0);
      vec3 lit = uColor * l;
      gl_FragColor = vec4(pow(lit, vec3(1.0 / 2.2)), uAlpha);
    }`;
  const LVS = `
    attribute vec3 aPos; uniform mat4 uProj, uView;
    void main() { gl_Position = uProj * uView * vec4(aPos, 1.0); }`;
  const LFS = `
    precision mediump float; uniform vec4 uColor;
    void main() { gl_FragColor = uColor; }`;

  function compile(src, type) {
    const s = gl.createShader(type);
    gl.shaderSource(s, src);
    gl.compileShader(s);
    return s;
  }
  function program(vs, fs) {
    const p = gl.createProgram();
    gl.attachShader(p, compile(vs, gl.VERTEX_SHADER));
    gl.attachShader(p, compile(fs, gl.FRAGMENT_SHADER));
    gl.linkProgram(p);
    return p;
  }
  function buffer(data, target, Type) {
    const b = gl.createBuffer();
    gl.bindBuffer(target, b);
    gl.bufferData(target, new Type(data), gl.STATIC_DRAW);
    return b;
  }

  const solid = program(VS, FS);
  const line = program(LVS, LFS);

  const parts = MODEL.parts.map(p => ({
    pos: buffer(p.points, gl.ARRAY_BUFFER, Float32Array),
    nrm: buffer(p.normals, gl.ARRAY_BUFFER, Float32Array),
    idx: buffer(p.indices, gl.ELEMENT_ARRAY_BUFFER, Uint16Array),
    count: p.indices.length,
    color: p.color,
  }));

  const lo = MODEL.min, hi = MODEL.max;
  const centre = [(lo[0] + hi[0]) / 2, (lo[1] + hi[1]) / 2, (lo[2] + hi[2]) / 2];
  const span = Math.max(hi[0] - lo[0], hi[1] - lo[1], hi[2] - lo[2]);

  // Floor grid: 10cm cells, 1m majors, sized to comfortably frame the model.
  const reach = Math.ceil((Math.max(span, 1.2) * 0.9) * 10) / 10 + 0.3;
  const minor = [], major = [];
  for (let i = -Math.round(reach * 10); i <= Math.round(reach * 10); i++) {
    const v = i / 10;
    const into = (Math.abs(i) % 10 === 0) ? major : minor;
    into.push(v, 0, -reach, v, 0, reach, -reach, 0, v, reach, 0, v);
  }
  const gridMinor = { buf: buffer(minor, gl.ARRAY_BUFFER, Float32Array), n: minor.length / 3 };
  const gridMajor = { buf: buffer(major, gl.ARRAY_BUFFER, Float32Array), n: major.length / 3 };

  const bb = [];
  const corner = (i, j, k) => [i ? hi[0] : lo[0], j ? hi[1] : lo[1], k ? hi[2] : lo[2]];
  for (const [a, b] of [
    [[0,0,0],[1,0,0]], [[1,0,0],[1,0,1]], [[1,0,1],[0,0,1]], [[0,0,1],[0,0,0]],
    [[0,1,0],[1,1,0]], [[1,1,0],[1,1,1]], [[1,1,1],[0,1,1]], [[0,1,1],[0,1,0]],
    [[0,0,0],[0,1,0]], [[1,0,0],[1,1,0]], [[1,0,1],[1,1,1]], [[0,0,1],[0,1,1]],
  ]) bb.push(...corner(...a), ...corner(...b));
  const boundsBuf = { buf: buffer(bb, gl.ARRAY_BUFFER, Float32Array), n: bb.length / 3 };

  function perspective(fovy, aspect, near, far) {
    const f = 1 / Math.tan(fovy / 2), d = near - far;
    return [f / aspect,0,0,0, 0,f,0,0, 0,0,(far + near) / d,-1, 0,0,(2 * far * near) / d,0];
  }
  function lookAt(eye, target, up) {
    const sub = (a, b) => [a[0]-b[0], a[1]-b[1], a[2]-b[2]];
    const norm = v => { const l = Math.hypot(...v) || 1; return [v[0]/l, v[1]/l, v[2]/l]; };
    const cross = (a, b) => [a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0]];
    const dot = (a, b) => a[0]*b[0] + a[1]*b[1] + a[2]*b[2];
    const z = norm(sub(eye, target)), x = norm(cross(up, z)), y = cross(z, x);
    return [x[0],y[0],z[0],0, x[1],y[1],z[1],0, x[2],y[2],z[2],0,
            -dot(x,eye), -dot(y,eye), -dot(z,eye), 1];
  }

  let az = 0.72, el = 0.32, dist = span * 2.5, spinning = true;
  let showGrid = true, showBounds = false;
  const clampEl = v => Math.max(-1.45, Math.min(1.45, v));

  const stage = canvas.parentElement;
  let dragging = false, lastX = 0, lastY = 0;
  stage.addEventListener("pointerdown", e => {
    if (e.target.tagName === "BUTTON") return;
    dragging = true; lastX = e.clientX; lastY = e.clientY;
    stage.setPointerCapture(e.pointerId);
    setSpin(false);
  });
  stage.addEventListener("pointermove", e => {
    if (!dragging) return;
    az -= (e.clientX - lastX) * 0.008;
    el = clampEl(el + (e.clientY - lastY) * 0.006);
    lastX = e.clientX; lastY = e.clientY;
  });
  const stop = () => { dragging = false; };
  stage.addEventListener("pointerup", stop);
  stage.addEventListener("pointercancel", stop);
  stage.addEventListener("wheel", e => {
    e.preventDefault();
    dist = Math.max(span * 0.6, Math.min(span * 8, dist * (1 + Math.sign(e.deltaY) * 0.11)));
  }, { passive: false });

  const spinBtn = document.getElementById("spin");
  function setSpin(on) {
    spinning = on;
    spinBtn.setAttribute("aria-pressed", String(on));
  }
  spinBtn.addEventListener("click", () => setSpin(!spinning));
  const toggle = (id, get, set) => {
    const b = document.getElementById(id);
    b.addEventListener("click", () => { set(!get()); b.setAttribute("aria-pressed", String(get())); });
  };
  toggle("grid", () => showGrid, v => showGrid = v);
  toggle("bbox", () => showBounds, v => showBounds = v);

  const reduced = matchMedia("(prefers-reduced-motion: reduce)");
  if (reduced.matches) setSpin(false);

  function drawLines(buf, n, proj, view, rgba, width) {
    gl.useProgram(line);
    gl.uniformMatrix4fv(gl.getUniformLocation(line, "uProj"), false, proj);
    gl.uniformMatrix4fv(gl.getUniformLocation(line, "uView"), false, view);
    gl.uniform4fv(gl.getUniformLocation(line, "uColor"), rgba);
    const a = gl.getAttribLocation(line, "aPos");
    gl.bindBuffer(gl.ARRAY_BUFFER, buf);
    gl.enableVertexAttribArray(a);
    gl.vertexAttribPointer(a, 3, gl.FLOAT, false, 0, 0);
    gl.lineWidth(width);
    gl.drawArrays(gl.LINES, 0, n);
  }

  function themeLine(varName) {
    const v = getComputedStyle(document.documentElement).getPropertyValue(varName).trim();
    const m = v.match(/rgba?\(([^)]+)\)/);
    if (!m) return [0.5, 0.5, 0.5, 0.3];
    const p = m[1].split(",").map(s => parseFloat(s));
    return [p[0] / 255, p[1] / 255, p[2] / 255, p.length > 3 ? p[3] : 1];
  }

  let last = performance.now();
  function frame(now) {
    const dt = Math.min((now - last) / 1000, 0.05);
    last = now;
    if (spinning) az += dt * 0.32;

    const dpr = Math.min(devicePixelRatio || 1, 2);
    const w = Math.round(canvas.clientWidth * dpr), h = Math.round(canvas.clientHeight * dpr);
    if (canvas.width !== w || canvas.height !== h) { canvas.width = w; canvas.height = h; }
    gl.viewport(0, 0, w, h);
    gl.clearColor(0, 0, 0, 0);
    gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
    gl.enable(gl.DEPTH_TEST);

    const target = [centre[0], centre[1] * 0.92, centre[2]];
    const eye = [
      target[0] + dist * Math.cos(el) * Math.sin(az),
      target[1] + dist * Math.sin(el),
      target[2] + dist * Math.cos(el) * Math.cos(az),
    ];
    const proj = perspective(0.62, w / h || 1, 0.02, 100);
    const view = lookAt(eye, target, [0, 1, 0]);

    if (showGrid) {
      drawLines(gridMinor.buf, gridMinor.n, proj, view, themeLine("--grid-minor"), 1);
      drawLines(gridMajor.buf, gridMajor.n, proj, view, themeLine("--grid-major"), 1.5);
    }

    gl.useProgram(solid);
    gl.uniformMatrix4fv(gl.getUniformLocation(solid, "uProj"), false, proj);
    gl.uniformMatrix4fv(gl.getUniformLocation(solid, "uView"), false, view);
    gl.uniform1f(gl.getUniformLocation(solid, "uAlpha"), 1);
    const aPos = gl.getAttribLocation(solid, "aPos");
    const aNrm = gl.getAttribLocation(solid, "aNrm");
    for (const p of parts) {
      gl.uniform3fv(gl.getUniformLocation(solid, "uColor"), p.color);
      gl.bindBuffer(gl.ARRAY_BUFFER, p.pos);
      gl.enableVertexAttribArray(aPos);
      gl.vertexAttribPointer(aPos, 3, gl.FLOAT, false, 0, 0);
      gl.bindBuffer(gl.ARRAY_BUFFER, p.nrm);
      gl.enableVertexAttribArray(aNrm);
      gl.vertexAttribPointer(aNrm, 3, gl.FLOAT, false, 0, 0);
      gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, p.idx);
      gl.drawElements(gl.TRIANGLES, p.count, gl.UNSIGNED_SHORT, 0);
    }

    if (showBounds) {
      gl.disable(gl.DEPTH_TEST);
      drawLines(boundsBuf.buf, boundsBuf.n, proj, view, themeLine("--grid-major"), 1.5);
    }
    requestAnimationFrame(frame);
  }
  requestAnimationFrame(frame);
}
</script>
"""


def read_layer(usdz_path):
    with zipfile.ZipFile(usdz_path) as zf:
        return zf.read(zf.infolist()[0]).decode("utf-8")


def floats(block):
    return [float(v) for m in re.findall(r"\(([^,)]+), ([^,)]+), ([^)]+)\)", block)
            for v in m]


def parse_meshes(usda):
    parts = []
    for chunk in usda.split("def Mesh ")[1:]:
        pts = re.search(r"point3f\[\] points = \[(.*?)\]", chunk, re.S)
        nrm = re.search(r"normal3f\[\] normals = \[(.*?)\]", chunk, re.S)
        idx = re.search(r"faceVertexIndices = \[(.*?)\]", chunk, re.S)
        col = re.search(r"displayColor = \[\(([^)]+)\)\]", chunk)
        if not (pts and nrm and idx):
            continue
        parts.append({
            "points": floats(pts.group(1)),
            "normals": floats(nrm.group(1)),
            "indices": [int(v) for v in idx.group(1).replace("\n", "").split(",") if v.strip()],
            "color": [float(v) for v in col.group(1).split(",")] if col else [0.7, 0.7, 0.7],
        })
    if not parts:
        raise SystemExit("no meshes found in %s" % usdz_path)
    return parts


def spec_rows(pairs):
    out = []
    for label, value in pairs:
        out.append('<div class="spec"><dt>%s</dt><dd>%s</dd></div>' % (label, value))
    return "".join(out)


def esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))


def build(usdz_path, title, meta):
    parts = parse_meshes(read_layer(usdz_path))
    xs = [c for p in parts for c in p["points"][0::3]]
    ys = [c for p in parts for c in p["points"][1::3]]
    zs = [c for p in parts for c in p["points"][2::3]]
    lo = [min(xs), min(ys), min(zs)]
    hi = [max(xs), max(ys), max(zs)]
    model = {"parts": parts, "min": lo, "max": hi}

    dims = [round((hi[i] - lo[i]) * 100) for i in range(3)]
    rows = [
        ("Width", '%d<span class="u"> cm</span>' % dims[0]),
        ("Depth", '%d<span class="u"> cm</span>' % dims[2]),
        ("Height", '%d<span class="u"> cm</span>' % dims[1]),
        ("Format", "USDZ"),
        ("Size", '%.1f<span class="u"> KB</span>' % (os.path.getsize(usdz_path) / 1024)),
    ]
    rows += [(k, esc(v)) for k, v in meta.items() if k.lower() not in ("eyebrow",)]

    eyebrow = esc(meta.get("eyebrow", os.path.basename(usdz_path)))
    note = (
        "<strong>Opening the file itself:</strong> on iPhone, iPad or Mac, tap or "
        "double-click the <code>.usdz</code> and Quick Look renders it — including "
        "an AR mode that places it in your room at this exact size. Windows, Android "
        "and Linux have no native USDZ support, which is what this page is for: the "
        "same geometry, same scale, in any browser."
    )
    html = (VIEWER_TEMPLATE
            .replace("__MODEL__", json.dumps(model, separators=(",", ":")))
            .replace("__TITLE__", esc(title))
            .replace("__HEADING__", esc(title))
            .replace("__EYEBROW__", eyebrow)
            .replace("__SPECS__", spec_rows(rows))
            .replace("__NOTE__", note))
    return html


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("usdz")
    ap.add_argument("-o", "--out")
    ap.add_argument("--title", default=None)
    ap.add_argument("--meta", action="append", default=[],
                    help="extra spec row, key=value (repeatable)")
    args = ap.parse_args()

    meta = {}
    for pair in args.meta:
        k, _, v = pair.partition("=")
        meta[k] = v
    title = args.title or os.path.basename(args.usdz)[:-5].replace("_", " ")
    out = args.out or (os.path.splitext(args.usdz)[0] + "_preview.html")
    with open(out, "w", encoding="utf-8") as f:
        f.write(build(args.usdz, title, meta))
    print("wrote %s" % os.path.normpath(out))


if __name__ == "__main__":
    main()
